# Generated by Django 4.2 on 2023-05-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('creada', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('actualizada', models.CharField(max_length=200, verbose_name='Actualizada')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('creada', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('actualizada', models.CharField(max_length=200, verbose_name='Actualizada')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('contenido', models.CharField(max_length=200, verbose_name='Contenido')),
                ('publicacion', models.BooleanField(default=True, verbose_name='Publicacion')),
                ('creada', models.DateField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('actualizada', models.DateField(auto_now=True, verbose_name='Fecha que se actualizo')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('creada', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('actualizada', models.CharField(max_length=200, verbose_name='Actualizada')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nombre'],
            },
        ),
    ]
