# Generated by Django 4.2 on 2023-05-02 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('creada', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('actualizada', models.DateField(auto_now=True, verbose_name='Fecha que se actualizo')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('creada', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('actualizada', models.DateField(auto_now=True, verbose_name='Fecha que se actualizo')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('creada', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('actualizada', models.DateField(auto_now=True, verbose_name='Fecha que se actualizo')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('contenido', models.CharField(max_length=200, verbose_name='Contenido')),
                ('publicacion', models.BooleanField(default=True, verbose_name='Publicacion')),
                ('creada', models.DateField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('actualizada', models.DateField(auto_now=True, verbose_name='Fecha que se actualizo')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.autor', verbose_name='Autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Manual',
                'verbose_name_plural': 'Manuales',
                'ordering': ['titulo'],
            },
        ),
    ]
