# Generated by Django 4.2 on 2023-05-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manual',
            options={'ordering': ['titulo'], 'verbose_name': 'Manual', 'verbose_name_plural': 'Manuales'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='actualizada',
            field=models.DateField(auto_now=True, verbose_name='Fecha que se actualizo'),
        ),
    ]
