# Generated by Django 4.2 on 2023-05-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_manual_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='actualizada',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha que se actualizo'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='creada',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='actualizada',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha que se actualizo'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='creada',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='manual',
            name='actualizada',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha que se actualizo'),
        ),
        migrations.AlterField(
            model_name='manual',
            name='creada',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='actualizada',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha que se actualizo'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='creada',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
    ]
