# Generated by Django 4.2 on 2023-05-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_alter_autor_actualizada_alter_autor_creada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='posts', verbose_name='Image'),
        ),
    ]
